### ISSUE TITLE
Rip out forward_progress tag stuff

### ISSUE THREAD

**Issue by mjgarland** [executors/issaquah_2016#13]
No one seems to believe that this is important, so let's remove it in the interest of simplicity.

**Comment by hcedwar** [comment]
I understood that the current mechanism should be removed, but some mechanism for exposing forward progress guarantees is important.

**Comment by mjgarland** [comment]
The leading candidate for such a mechanism would be new method names that specify their semantics I believe, right?

**Comment by hcedwar** [comment]
I heard discussion - but not consensus - an open question.
