### ISSUE TITLE
Consider adding a Terminology section

### ISSUE THREAD

**Issue by mjgarland** [executors/issaquah_2016#14]
We should consider adding a Terminology section to define terms such as "executor" and "execution context" in one place.  This might help in avoiding misunderstanding, especially since we've started using terms that are pretty similar (e.g., "execution context" and "execution resource"), and improve the readability of the paper.

I know of at least three sources of possible definitions:  the slides I presented contain some (sketchy) definitions, the material Chris Kohlhoff wrote last month, and the material Carter Edwards wrote following the teleconference where Chris presented his write up.  If we have settled on common definitions for essential terms, we should make sure these are reflected in the paper draft.

**Comment by fraggamuffin** [comment]
Definitely need it. May be even a rationale section?

**Comment by hcedwar** [comment]
The shared github document is the proper place to iterate-to-agreement on definitions, we do not need to wait until consensus before adding anything to the work-in-progress.

**Comment by mjgarland** [comment]
Terminology section added by pull request #24
