### ISSUE TITLE
Consider renaming these two executor type traits

### ISSUE THREAD

**Issue by jaredhoberock** [executors/issaquah_2016#163]
In explaining how the executor type traits work, it occurs to me that there may be an opportunity to improve the naming of a couple of the traits to increase clarity and consistency.

What do people think of these name changes? Are they improvements?

* `executor_execute_blocking_category` -> `executor_execute_blocking_guarantee`
* `executor_execution_category` -> `executor_bulk_ordering_guarantee`

The `category` naming scheme was inspired by `iterator_category`, but the things we're describing aren't really categories, and anyway we use the term "executor category" to describe something completely different. The things we want to communicate with respect to blocking and bulk execution are guarantees.

I'd also consider eliminating the `_tag` suffixes on the possible values for these traits because it's another iterator trait-inspired thing that just seems like noise.

**Comment by jaredhoberock** [comment]
"ordering" may not be the right word for the bulk guarantee. We'll eventually want to guarantee concurrency among agents in a group, and "concurrent order" doesn't really sound right to me.

**Comment by jaredhoberock** [comment]
Some sort of name including the phrase "forward progress" might be what we should use here.

**Comment by AerialMantis** [comment]
I agree, these properties make more sense as guarantees than as categories, it might also make it easier to talk about the properties in relation to each other, for example `non_blocking_execution` could be a described as being a higher guarantee than `possibly_blocking_execution`.

I like the names `executor_execute_blocking_guarantee` and `bulk_forward_progress_guarantee`.

**Comment by jaredhoberock** [comment]
Fixed by #192
