### ISSUE TITLE
Consider promoting .context() to be a customization point

### ISSUE THREAD

**Issue by jaredhoberock** [executors/issaquah_2016#164]
Our current proposal requires every executor to define a `.context()` member function. Right now, it is the only interface requiring clients to go directly through a member rather than indirectly through a customization point or type trait. Moreover, if an executor type does not have an independent context they are allowed act as their own context, because all executor types trivially fulfill our small list of requirements for execution contexts.

It seems like we could improve the uniformity of our design and further eliminate a small extra requirement of executor authors (the `.context()` member function) if we introduced the customization point `execution::context(executor)`. Its behavior would be simple:

  * If `executor.context()` is well-formed, return its result; otherwise
  * if `context(executor)` is well-formed, return its result; otherwise
  * `return executor`

**Comment by ccmysen** [comment]
The last property would imply then that any copy of the executor would actually not be the same context (e.g. passing an executor to a function by value would then place it in a unique context)?

I think the customization point is consistent, though i'm not entirely sure there is a meaningful way for external code to know how to infer or generate a context, it seems like something that must come from the executor.

I think it's okay to say that it's acceptable for an executor to return itself as the context, but probably undesirable to do so unless no other context exists.

**Comment by jaredhoberock** [comment]
Yes to customization point, no to default. Third bullet should be ill-formed.

**Comment by jaredhoberock** [comment]
Apply the same rationale to the work tracking functions. Third bullet should be ill-formed.

**Comment by jaredhoberock** [comment]
Decided against merging #193 on June 9, 2017 telecon
