### ISSUE TITLE
static_thread_pool::attach Note is unclear

### ISSUE THREAD

**Issue by TBBle** [executors/issaquah_2016#184]
`static_thread_pool::attach` currently has the following Note: (Bold by me)
> (Note: The implementation **is required** to use the attached thread to execute submitted function objects. RATIONALE: implementations in terms of the Windows thread pool cannot utilise user-provided threads. --end note)

Apart from the oddity of having a requirement in a Note, this also seems to be producing the opposite requirement to the given rationale, requiring something impossible from the Windows thread pool.

The previous text (before #103, see 1ae548c13e62c46544ea11fc5906ea2e33d20d31) was (Bold by me)
> (Note: The implementation is **encouraged, but not required**, to use the attached thread to execute submitted function objects. RATIONALE: implementations in terms of the Windows thread pool cannot utilise user-provided threads. --end note)

Was the sense reversal intentional (per https://github.com/executors/issaquah_2016/pull/103#issuecomment-277089774 and https://github.com/executors/issaquah_2016/pull/103#discussion_r99402676) in which case the RATIONALE is confusing, or did a 'not' get lost during text editing?

**Comment by chriskohlhoff** [comment]
I created pull request #187 for this.

**Comment by jaredhoberock** [comment]
Fixed by #187
