### ISSUE TITLE
Where does Function template execution::execute() come from? 

### ISSUE THREAD

**Issue by fraggamuffin** [executors/issaquah_2016#19]
Is this in the root? There is no mention of this anywhere else but in Customization point:
Function template execution::execute()

**Comment by fraggamuffin** [comment]
Ok I see that it is the return of the invoke further down.

**Comment by fraggamuffin** [comment]
I think this is fixed now when @chriskohlhoff changed the name from spawn_execute() to execute().

**Comment by mjgarland** [comment]
This appears ready to close, right?
