### ISSUE TITLE
Is there a dynamic (may-block) state for blocking behaviour?

### ISSUE THREAD

**Issue by fraggamuffin** [executors/issaquah_2016#23]
We have blocking and non-blocking. Some people seem to talk about may-block, implying a dynamically changeable quality. Is there serious consideration to support this?

**Comment by jaredhoberock** [comment]
Yes, the function named `.execute()` may or may not block the caller, and I don't believe anything in the current wording of the paper would prevent `.execute()` from having dynamic blocking behavior. From the perspective of the assumptions the client places on the executor, `.execute()` still may or may not block.

An earlier revision of the paper allowed an executor to advertise through the type system whether or not its operations blocked. There were three choices: blocks, does not block, and possibly blocks. There was strong opposition to this feature, so we removed it after the first phone meeting.

**Comment by fraggamuffin** [comment]
OK, this can close if you are saying that .execute() can be set to block or not block, and once set cannot be changed at runtime, dynamically. And it stays the same behavior from invocation to invocation of the same code.

**Comment by jaredhoberock** [comment]
Propose to close
