### ISSUE TITLE
Respond to Toronto concerns over execution::prefer

### ISSUE THREAD

**Issue by jaredhoberock** [executors/issaquah_2016#245]
Straw poll: OK with `execution::prefer` as-is?
```
SF F  N A SA
2  3 13 3 2
```

Geoff: Are users using `prefer` to change API contracts, and if so, is it intentional?
Pablo: I think hint-like properties can be restructured as requirements.

**Comment by jaredhoberock** [comment]
Summarizing our August 4 discussion:

We definitely want to retain `execution::prefer` because it is a valuable signal of user intent.

Moreover, there was a consensus that the blocking properties should remain compatible with `execution::prefer`, because this use case corresponds to existing practice.

There was a consensus that `execution::prefer` need not be compatible with executor properties which introduce execution functions. However, we see use cases for preferences which introduce other kinds of executor member functions. Since such member functions would be less fundamental than execution functions, we are comfortable with this trade-off.

Our tentative plan is to design some way of indicating that particular properties are only compatible with `execution::require` (or possibly the other way around with `execution::prefer`).

Uncontroversial properties such as the cardinality and directionality properties would only be compatible with `execution::require`.

Controversial properties such as the blocking properties need some sort of justification for why they can be `execution::prefer`ed. Additionally, we may wish that these properties be allowable as preferences only in certain cases, such as when preferring `non_blocking` from a `possibly_blocking` executor.

**Comment by jaredhoberock** [comment]
Here is a simple approach to "unpreferable" properties I experimented with:

```
// a base class for properties which are unusable with execution::prefer()
struct unpreferable {};

template<class Executor>
void prefer(Executor&& exec, unpreferable) = delete;
```

It almost does what I expect with our prototype implementation. There is an issue with the `prefer` free function above being ambiguous with the `execution::prefer` customization point. A test program is pasted below.

```
#include <experimental/execution>

namespace std {
namespace experimental {
inline namespace concurrency_v2 {
namespace execution {


// a base class for properties which are unusable with execution::prefer()
struct unpreferable {};

template<class Executor>
void prefer(Executor&& exec, unpreferable) = delete;


struct test_t : unpreferable {};

constexpr test_t test{};


} // namespace execution
} // inline namespace concurrency_v2
} // namespace experimental
} // namespace std


struct my_executor
{
  template<class F>
  void execute(F f) const
  {
    f();
  }
};

struct my_executor2
{
  template<class F>
  void execute(F f) const
  {
    f();
  }

  // opt-in to allowing unpreferable preferences through .prefer()
  my_executor2 prefer(std::experimental::concurrency_v2::execution::test_t) const
  {
    return *this;
  }
};


int main()
{
  using namespace std::experimental::concurrency_v2::execution;

  {
    my_executor exec;

    // this line does not compile and works as expected.
    // the compiler error message is:
    //
    //     test_unpreferable.cpp:13:6: note: candidate function [with Executor = my_executor &] has been explicitly deleted
    //     void prefer(Executor&& exec, unpreferable) = delete;
    //
    auto test_exec1 = std::experimental::concurrency_v2::execution::prefer(exec, test);

    // this line does not compile and does not work as expected.
    // the compiler error message is:
    //
    //     test_unpreferable.cpp:67:21: error: reference to 'prefer' is ambiguous
    //     auto test_exec1 = prefer(exec1, test);
    //          ^
    //     test_unpreferable.cpp:13:6: note: candidate found by name lookup is 'std::experimental::concurrency_v2::execution::prefer'
    //     void prefer(Executor&& exec, unpreferable) = delete;
    //          ^
    //    include/experimental/execution:100:25: note: candidate found by name lookup is 'std::experimental::concurrency_v2::execution::(anonymous namespace)::prefer'
    //      constexpr const auto& prefer = prefer_impl::customization_point<>;
    //                            ^
    auto test_exec2 = prefer(exec, test);
  }

  {
    my_executor2 exec;

    // this line does not compile and works as expected(?).
    // the compiler error message is:
    //
    //     test_unpreferable.cpp:84:23: error: call to deleted function 'prefer'
    //     auto test_exec1 = std::experimental::concurrency_v2::execution::prefer(exec, test);
    //                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //     test_unpreferable.cpp:13:6: note: candidate function [with Executor = my_naughty_executor &] has been explicitly deleted
    //     void prefer(Executor&& exec, unpreferable) = delete;
    // 
    auto test_exec1 = std::experimental::concurrency_v2::execution::prefer(exec, test);

    // this line does compile and works as expected(?).
    auto test_exec2 = exec.prefer(test);
  }
}
```

**Comment by chriskohlhoff** [comment]
I created #255 to show the traits-based change I had in mind during the last call.

However, I do think the use of deleted functions shown above is better. Even better, it is much cleaner if we also remove the requirement for executors to provide a prefer member function. That way `prefer` becomes purely a customization point / external algorithm. I created #256 to show how this works.

I think there's a problem with the customization point implementation which causes the compiler errors above. I worked around it by putting the deletions in the customization point's implementation namespace. The appproach works in a property that is defined outside `std` (see hints/defaulted_3.cpp).

**Comment by ccmysen** [comment]
Chris, when thinking about the interaction with the polymorphic executor, i was not totally clear on the requirement on the polymorphic executor.

It seems that if we go purely customization, then prefer is actually just syntactic sugar on require() such that prefer may chose to return the same executor or a new executor which has the new functionality. 

it would be analogous to calling:
if (can_require(x))
  return require(ex, x);

in which case can_prefer and prefer members would just go away on the polymorphic executor, correct? or would there still be a reason to natively implement this in the executor still?

**Comment by ccmysen** [comment]
I spoke with Geoff about his concerns and his primary concern was that you can call prefer and get semantic changes which you then unintentionally begin to rely on in what looks like generic code. This is maybe less of an issue when the API changes or expands since you need to be aware of API differences depending on the traits applied. But when there are semantic changes in a prefer call you risk code "working" simply because the executors tested behaved in one of the possible ways (probably more likely you rely on the "prefer"ed traits and stop working when default behavior is applied).

This becomes more complex when you start passing executors with preferences applied to other generic code which applies its own preferences on top, which then makes it more and more difficult to test your generic code effectively.

I think a core fix to this is not obvious because that's the whole point of being able to prefer (that you claim it doesn't matter which behavior you need and so whatever behavior is fine). Though perhaps the answer here is that code can check the traits to see what behavior to expect.
