### ISSUE TITLE
Better working names for execute functions

### ISSUE THREAD

**Issue by chriskohlhoff** [executors/issaquah_2016#25]
Yes, bikeshedding names is under LEWG's purview, however I find `spawn_execute` and `async_execute` unwieldy. I'd like to propose that we use these working names for the execute functions. These are in part based on existing proposals.

* `execute` - one-way, may or may not block caller
* `invoke` - two-way, always blocks caller (so named because std::invoke satisfies these requirements)
* `async_invoke` - two-way, not required to block caller, returns a future result 
* `post` - one-way, may not block caller, indicates no continuation relationship between caller and callee
* `defer` - one-way, may not block caller, indicates continuation relationship between caller and callee

**Comment by hcedwar** [comment]
Alternative perspective.  If a particular executor acting on a given execution resource were have exactly one execute method and each executor required to specify its execution properties (one/two way, block/nonblock, return type, ... ) as in https://github.com/executors/issaquah_2016/pull/24 then bikeshedding is unnecessary and the function can be `execute` or even `operator()`.

**Comment by mjgarland** [comment]
Alternative names discussed on the phone:
execute,
sync_execute, (rather than invoke)
async_execute (rather than async_invoke)
