### ISSUE TITLE
Continuation interfaces should not be part of this 

### ISSUE THREAD

**Issue by hkaiser** [executors/issaquah_2016#27]
The functions which take a future object to express a dependency for the executor operation to perform should not be part of this proposals (e.g. `then_execute()`, `bulk_then_execute()`, etc.)

Rationale: 

 - This functionality increases the necessary interface executor would have to implement with questionable gain.
 - This function unnecessarily duplicates functionality already available from the Concurrency TS in combination with functionality available from other parts of this proposal. Instead of writing

        future<T> fut = ...;
        exec,then_execute([](T) {...}, fut); 

    one could easily write:

        future<T> fut = ...
        fut.then(exec, [](future<T> fut)
        {
            execution::execute(exec, [](T) {...}, fut.get()); 
        });

 - (related): This style of interface is too limiting as only one future can be passed as a 'predecessor'. In order to specify more than one predecessor one would have to use `when_all()` (Concurrency TS) or similar, in which case the required functionality could be directly attached to the future returned from `when_all()` (see above).

**Comment by jaredhoberock** [comment]
After a phone call with Hartmut, we agreed that the paper should retain the continuation interfaces, and also that the paper should also describe how executors compose with `when_all()` (#37).

**Comment by jaredhoberock** [comment]
Proposed resolution: close this bug
