### ISSUE TITLE
Exceptional behavior of execute

### ISSUE THREAD

**Issue by jaredhoberock** [executors/issaquah_2016#3]
What should the effects of `execution::execute()` be if an exception propagates from `f`?

**Comment by fraggamuffin** [comment]
Do we have a summary of this from last call's discussion? I seem to recall Michael Garland wrote something during the call.

**Comment by jaredhoberock** [comment]
From memory, the idea is that the two-way executor operations will propagate exceptions from execution agents. Synchronous operations would throw the exception directly, while asynchronous operations will return an exceptional future.

Executors providing one-way operations can do something different at their own discretion because there is no obvious channel for communicating the exception back to the caller.

I'll integrate this into the paper before the next meeting.

**Comment by fraggamuffin** [comment]
We love it :)
