### ISSUE TITLE
What is a sensible implementation of .then_execute?

### ISSUE THREAD

**Issue by chriskohlhoff** [executors/issaquah_2016#45]
Can we have an example of how to implement this for someone writing a TwoWayExecutor

**Comment by jaredhoberock** [comment]
Here's an implementation of `.bulk_then_execute()` for an executor backed by a thread pool. The complete implementation is [here](https://github.com/jaredhoberock/agency/blob/issue-248/agency/detail/concurrency/thread_pool.hpp#L248).

```
template<class Function, class Future, class ResultFactory, class SharedFactory>
std::future<
  result_of_t<ResultFactory()>
>
bulk_then_execute(Function f, size_t n, Future& predecessor, ResultFactory result_factory, SharedFactory shared_factory)
{
  using result_type = result_of_t<ResultFactory()>;

  // create a shared promise to fulfill the result
  auto shared_promise_ptr = std::make_shared<std::promise<result_type>>();

  // get the shared promise's future
  auto result_future = shared_promise_ptr->get_future();

  // create a deleter which fulfills the promise with the result and then deletes the result
  fulfill_promise_and_delete<result_type> deleter{std::move(shared_promise_ptr)};

  // create the shared state for the result
  auto shared_result_ptr = std::shared_ptr<result_type>(new result_type(result_factory()), std::move(deleter));

  // create the shared state for the shared parameter
  using shared_arg_type = result_of_t<SharedFactory()>;
  auto shared_arg_ptr = std::make_shared<shared_arg_type>(shared_factory());

  // share the incoming future
  auto shared_predecessor = future_traits<Future>::share(predecessor);

  // submit n tasks to the thread pool
  for(size_t idx = 0; idx < n; ++idx)
  {
    system_thread_pool().submit([=]() mutable
    {
      // wait on the predecessor future
      shared_predecessor.wait();

      // call the user's function
      f(idx, *shared_result_ptr, *shared_arg_ptr);

      // we explicitly release shared_result_ptr because even though this
      // lambda's invocation is complete, the lambda's lifetime
      // (and therefore shared_result_ptr's lifetime) is not necessarily complete
      // this .reset() is what fulfills the promise via shared_result_ptr's deleter
      shared_result_ptr.reset();
    });
  }

  // return the result future
  return std::move(result_future);
}
```

We also have an implementation for a special type of future (i.e., not `std::future`) corresponding to work executing on a GPU. It's probably too long to post here, but the gist of it goes like this:

```
template<class Function, class T, class ResultFactory, class SharedFactory>
cuda::future<result_of_t<ResultFactory()>>
bulk_then_execute(Function f, size_t n, cuda::future<T>& predecessor, ResultFactory result_factory, SharedFactory shared_factory)
{
  // create the state for the result
  auto result_state = ...

  // create the state for the shared parameter
  auto shared_parameter = ...

  // launch the work and make it depend on the completion of the predecessor
  auto next_event = create_gpu_work(f, n, predecessor.event(), predecessor.state(), result_state, shared_state);

  // return a future corresponding to the completion of the next event
  return cuda::future<...>(next_event, result_state);
}
```

**Comment by chriskohlhoff** [comment]
I think I need to take a step back and ask when do you expect then_execute to be used. Is it:

- As the implementation of future::then, to allow executors to customise this; or

- In algorithms, which call then_execute instead of calling future::then directly, giving the executor an opportunity to customise the behaviour associated with a dependency relationship?

**Comment by jaredhoberock** [comment]
I expect `then_execute()` to be used in both of those scenarios.

`then_execute()` is intended to be more primitive than `future::then()`, analogously to how `async_execute()` is more primitive than `std::async()`. In other words, `future::then(continuation)` would just be sugar for some call to `then_execute(default_exec, continuation, future)` called on some default executor `default_exec`.

Algorithms could schedule dependent work on executors either through `future::then()` or `then_execute()` or other control structures as is convenient.

So, yes -- the purpose of introducing the customization point `then_execute()` is to provide executors the opportunity of customizing the execution of the continuation.

**Comment by chriskohlhoff** [comment]
So given a user-defined two-way executor (let's say it logs on entry to and exit from a task), which uses a .then()-capable std::future, how do you intend the blanks be filled in here:

    class my_executor
    {
    public:
      template <class T> using future = std::future<T>;
      // ...
      ??? then_execute(F&& f, ???)
      {
         ???
      }
    };

**Comment by jaredhoberock** [comment]
Assuming that `my_executor::execute()` exists and introduces the customization you describe, `then_execute()` could work something like this:

```
class my_executor
{
  public:
    template<class Function>
    void execute(Function&& f); // an execute() with customized behavior

    template<class Function, class Future>
    auto then_execute(Function&& f, Future& predecessor)
    {
      // create a function to wait on the future and invoke f
      auto g = [f=std::move(f), predecessor=std::move(predecessor)]
      {
        auto pred = predecessor.get(); // this line assumes this is not a void future
        return f(pred);
      };

      using result_type = std::result_of_t<decltype(g)()>;

      // package g for execution
      std::packaged_task<result_type()> execute_me(std::move(g));

      // get the future to return
      auto result_future = execute_me.get_future();

      // execute the packaged task
      this->execute(std::move(execute_me));

      // return the future
      return std::move(result_future);
    }
};
```

**Comment by chriskohlhoff** [comment]
Are you sure this is correct? It never seems to attach a continuation to the predecessor future, but will instead hog a thread in the thread pool to wait for it to become ready. Is that the intention?

**Comment by jaredhoberock** [comment]
That's a good point. You're absolutely correct that it consumes an execution agent to wait for the future to become ready. I suppose how efficient that is depends on the capabilities of the underlying execution context.

In the case of a fixed-size thread pool, one would want to avoid submitting to the pool until the continuation is ready to run. One option would be to move the predecessor future into a list of not-yet-ready futures which are periodically checked for readiness. Once a future is ready, the packaged task above could be submitted to the thread pool. Does that make sense?

**Comment by ccmysen** [comment]
Wouldn't you want the previous version to use future::then(executor) as a default implementation of sort? I don't know that i see then_execute as more primitive when future::then is properly defined. Basically, i would see sort of an alternative implementation where you assume that future::then does the right thing w.r.t. either immediately queueing on the executor if done or doing so as a continuation after completion.

Or do you see the idea that future::then will call then_execute (i don't see that being functionally correct to be honest since future::then will need to take an executor which would require then_execute would also be able to take an alternative executor).

```
class my_executor
{
  public:
    template<class Function>
    void execute(Function&& f); // an execute() with customized behavior

    template<class Function, class Future>
    auto then_execute(Function&& f, Future& predecessor)
    {
      using result_type = std::result_of_t<decltype(g)()>;

      // package g for execution
      std::packaged_task<result_type()> execute_me(std::move(predecessor));

      // get the future to return
      auto pred_future = execute_me.get_future();
      auto result_future = pred_future.then(this, std::move(f));
      return std::move(result_future);
    }
  }
}
```

**Comment by jaredhoberock** [comment]
> Wouldn't you want the previous version to use future::then(executor) as a default implementation of sort? I don't know that i see then_execute as more primitive when future::then is properly defined. 

I was hoping we could simplify futures by quarantining the complexity of execution agent creation to the executor customization points. The idea is that `future::then(executor, func)` would simply lower onto `execution::then_execute(executor, func)`. The overload of `future::then(func)` without an executor parameter could call `future::then(some_executor, func)`, where `some_executor` is some default executor particular to the future type.

**Comment by chriskohlhoff** [comment]
As an aid to discussion, this doesn't accord with my understanding of how future.then would be implemented. Assuming a non-executor implementation of future.then (simplified) that looks something like this (showing just the future state that would be shared between the future and promise)

    template <class T>
    class future_state
    {
        std::mutex mutex_;
        T value_;
        std::function<void(std::future<T>)> func_;
        enum { unset, set } state_ = unset;

    public:
        std::future<T> to_future();

        template <class F>
        std::future<result_of<F()>> then(F f)
        {
            std::packaged_task<void(std::future<T>)> pkg(f);
            std::future<T> fut = pkg.get_future();
            std::mutex::scoped_lock<std::mutex> lock(mutex_);
            if (state_ == set)
            {
                lock.unlock();
                pkg(to_future());
            }
            else
            {
                func_ = std::move(pkg);
            }
            return fut;
        }

        void set_value(T t)
        {
            std::mutex::scoped_lock<std::mutex> lock(mutex_);
            if (state_ == set)
            {
                throw std::future_error(std::future_errc::promise_already_satifisfied);
            }
            else
            {
                value_ = std::move(t);
                state_ = set;
                if (func_)
                {
                    auto f = std::move(func_);
                    lock.unlock();
                    f(to_future());
                }
            }
        }
    };

If executors are added, then I believe the changes look something like this:

    template <class T>
    class future_state
    {
        std::mutex mutex_;
        T value_;
        std::function<void(std::future<T>)> func_;
        enum { unset, set } state_ = unset;

    public:
        std::future<T> to_future();

        template <class E, class F>
        std::future<result_of<F()>> then(E e, F f)
        {
            std::packaged_task<void(std::future<T>)> pkg(f);
            std::future<T> fut = pkg.get_future();
            std::mutex::scoped_lock<std::mutex> lock(mutex_);
            if (state_ == set)
            {
                lock.unlock();
                e.execute([pkg=std::move(pkg),fut=to_future()]{ pkg(fut); }); // HERE 
            }
            else
            {
                func_ = std::move(pkg);
            }
            return fut;
        }

        void set_value(T t)
        {
            std::mutex::scoped_lock<std::mutex> lock(mutex_);
            if (state_ == set)
            {
                throw std::future_error(std::future_errc::promise_already_satifisfied);
            }
            else
            {
                value_ = std::move(t);
                state_ = set;
                if (func_)
                {
                    auto e = std::move(exec_);
                    auto f = std::move(func_);
                    lock.unlock();
                    e.execute([f=std::move(f),fut=to_future()]{ f(fut); }); // HERE
                }
            }
        }
    };

The storage of the continuation (and the executor that will be used to invoke it) is closely couple to the future implementation.

**Comment by mjgarland** [comment]
Discussion points from teleconference:
- std::future::then should accept a particular type of one-way executor (that can't block in execute())
- keep .then vague with sketchy pseudo-code to indicate future direction rather than precise semantics
- Switch things around so that future::then() is more fundamental than then_execute()
