### ISSUE TITLE
Behaviour of execution context destructor

### ISSUE THREAD

**Issue by AerialMantis** [executors/issaquah_2016#52]
In the last call we discussed the behaviour of the execution context/resource destructor, there was a suggestion that it should call stop() and then attach(), though I don't believe we decided on it.

I would like to propose that the execution context is not required to call stop(), making that optional, as some runtimes such as SYCL wait for all currently executing functions to finish during destruction of the runtime scheduler.

**Comment by mjgarland** [comment]
I don't recall discussing any such requirement.  There are very few requirements on execution contexts in the current draft.  At the moment, the only requirement is EqualityComparable.

**Comment by mjgarland** [comment]
Unless I've missed something, I don't think there's anything we need to address here because the paper doesn't place these restrictions on execution contexts.  I propose we close this issue.

**Comment by AerialMantis** [comment]
Okay, if there's no requirements on the waiting behaviour of the context destructor, this is fine and we can close this.
