### ISSUE TITLE
What kind of threads are in thread_pool?

### ISSUE THREAD

**Issue by mjgarland** [executors/issaquah_2016#53]
Are the threads in `thread_pool` guaranteed to have the same capabilities and semantics of `std::thread`?  The text does not appear to say one way or the other at the moment.

**Comment by mjgarland** [comment]
The text on the constructor does indeed mention `std::thread`, but without the `std::` qualifier.

**Comment by chriskohlhoff** [comment]
Addressed by pull request #68
