### ISSUE TITLE
Bulk executor traits have tags that seem to not relate to forwrd progress guarantees

### ISSUE THREAD

**Issue by fraggamuffin** [executors/issaquah_2016#57]
Do these tags relate to forward progress guarantees?
struct sequenced_execution_tag {};
struct parallel_execution_tag {};
struct unsequenced_execution_tag {};

In particular, there a TODO that mentions the need to specify how executor_execution_category_t describes the forward progress requirements of a group of execution agents wrt each other which may be what we are looking for.

**Comment by mjgarland** [comment]
Yes, they do, and that is what the TODO is about.  Those execution category tags are meant to correspond to the execution policies in C++17.  They serve to advertise what forward progress guarantees an executor provides amongst the set of agents created by bulk_async_execute(), for example.  It is part of the mechanism for coupling executors with C++17 parallel algorithms and other parts of the Parallelism TS v2.
