### ISSUE TITLE
Bad markdown

### ISSUE THREAD

**Issue by fraggamuffin** [executors/issaquah_2016#59]
Function template execution::sync_execute()

``````
``` template result_of_t()> sync_execute(Executor& exec, Function&& f);
``````

Function template execution::then_execute()

``````
``` template executor_future_t then_execute(Executor& exec, Function&& f, Future& predecessor);
``````

Function template execution::bulk_sync_execute()

``````
``` template result_of_t bulk_sync_execute(Executor& exec, Function1 f, executor_shape_t shape, Function2 result_factory, Function3 shared_factory);
``````

Function template execution::bulk_then_execute()

``````
``` template executor_future_t< Executor, result_of_t > bulk_then_execute(Executor& exec, Function1 f, executor_shape_t shape, Future& predecessor, Function2 result_factory, Function3 shared_factory);
``````

**Comment by jaredhoberock** [comment]
Thanks, I think I see what you mean. It looks like this may just be a bug in Github's rendering of the Markdown, because these issues don't show up in the paper as generated by Pandoc.

**Comment by mjgarland** [comment]
This appears to be rendering correctly at the moment, including on the GitHub page.
