### ISSUE TITLE
where did Function template execution::sync_execute() come from?

### ISSUE THREAD

**Issue by fraggamuffin** [executors/issaquah_2016#60]
We don't believe Function template execution::sync_execute() is a customization point. May be left over from previous draft?

**Comment by fraggamuffin** [comment]
Or is TwoWayExecutor missing the sync_execute that needs to be added for symmetry?

**Comment by fraggamuffin** [comment]
If the last assertion is correct, then it is also missing from the 
Class two_way_executor
Polymorphic wrapper

**Comment by mjgarland** [comment]
Should add the sync_execute method to this table:
Table: (Two-Way Executor requirements) \label{two_way_executor_requirements}
