### ISSUE TITLE
Embellish introduction with examples of how to define custom executors

### ISSUE THREAD

**Issue by jaredhoberock** [executors/issaquah_2016#65]
Embellish with a couple of examples of how to define executors.

Custom executor idea: adaptation of another executor that would add logging
OpenMP executor example: Start with one-way executor (OpenMP task), then show how to add an additional customization point for bulk-two-way (omp parallel for).

**Comment by chriskohlhoff** [comment]
A trivial inline executor (e.g. one that simply logs and invokes, i.e. not an adapter) might also be a good example.
