### ISSUE TITLE
bulk_execute : connection between f(i,r,s) and {n,fr,fs} is unclear

### ISSUE THREAD

**Issue by hcedwar** [executors/issaquah_2016#7]
In bulk_execute the connection between f(i,r,s) and {n,fr,fs} should be clearly specified.

**Comment by fraggamuffin** [comment]
This should probably be closed as this is answered in #9.
rf is result factory
and 
sf is shared factory

**Comment by mjgarland** [comment]
Closing because this seems to have been addressed.
